# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name
name: Build and test Node CI

# condition trigger
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# what to do aka jobs
jobs:
  build-and-test:
    # platform
    runs-on: ubuntu-latest
    # strategy (optional)
    # actions
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
